runtime: python39

entrypoint: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --timeout 120

instance_class: F2

env_variables:
  PINECONE_API_KEY: "pcsk_2ByS83_Rd4pm21uWJ5mWXKjaPRyhJDqLYbr3RVueSu9iJ2W84iXSyXqzrVqpeKM53JCj8S"
  OPENAI_API_KEY: "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"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65 
